"""Adding Words and Characters tables

Revision ID: f674fb1e524a
Revises: 1b40d5775cd1
Create Date: 2022-12-23 22:30:42.379546

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "f674fb1e524a"
down_revision = "1b40d5775cd1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "characters",
        sa.Column("character", sa.String(length=1), nullable=False),
        sa.Column("definition", sa.String(length=150), nullable=True),
        sa.Column("pinyin", sa.String(length=50), nullable=False),
        sa.Column("decomposition", sa.String(length=15), nullable=True),
        sa.Column("etymology", sa.JSON(), nullable=True),
        sa.Column("radical", sa.String(length=1), nullable=False),
        sa.Column("matches", sa.String(length=300), nullable=False),
        sa.Column("frequency", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_characters")),
    )
    op.create_index(op.f("ix_characters_id"), "characters", ["id"], unique=False)
    op.create_table(
        "words",
        sa.Column("simplified", sa.String(length=50), nullable=False),
        sa.Column("traditional", sa.String(length=50), nullable=False),
        sa.Column("pinyin_num", sa.String(length=150), nullable=False),
        sa.Column("pinyin_accent", sa.String(length=100), nullable=False),
        sa.Column("pinyin_clean", sa.String(length=100), nullable=False),
        sa.Column("pinyin_no_spaces", sa.String(length=100), nullable=False),
        sa.Column("also_written", sa.String(length=75), nullable=False),
        sa.Column("also_pronounced", sa.String(length=75), nullable=False),
        sa.Column("classifiers", sa.String(length=25), nullable=False),
        sa.Column("definitions", sa.String(length=500), nullable=False),
        sa.Column("frequency", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_words")),
    )
    op.create_index(op.f("ix_words_id"), "words", ["id"], unique=False)
    op.create_table(
        "word_characters",
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("character_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["character_id"], ["characters.id"], name=op.f("fk_word_characters_character_id_characters")
        ),
        sa.ForeignKeyConstraint(["word_id"], ["words.id"], name=op.f("fk_word_characters_word_id_words")),
        sa.PrimaryKeyConstraint("word_id", "character_id", name=op.f("pk_word_characters")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("word_characters")
    op.drop_index(op.f("ix_words_id"), table_name="words")
    op.drop_table("words")
    op.drop_index(op.f("ix_characters_id"), table_name="characters")
    op.drop_table("characters")
    # ### end Alembic commands ###
