version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity


  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: cnlearn
      POSTGRES_PASSWORD: postgres
      ENVIRONMENT: Development
    ports:
      - 5432:5432

  testing_db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data-testing:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: cnlearn_testing
      POSTGRES_PASSWORD: postgres
      ENVIRONMENT: Testing
    ports:
      - 5433:5432
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgres-data:
  postgres-data-testing:
