name: Run flake8, black and pytest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Run ruff for linting
        run: poetry run ruff .

      - name: Run black --check .
        run: poetry run black --check .

      - name: Run mypy
        run: poetry run mypy .

      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: "15"
          postgresql db: "cnlearn_testing"
          postgresql user: "postgres"
          postgresql password: "postgres" # add this to secret

      - name: Wait / Sleep
        uses: jakejarvis/wait-action@v0.1.0
        with:
          time: "10s"

      - name: Collect Docker Logs
        uses: jwalton/gh-docker-logs@v1.0.0

      - name: Check running containers
        run: docker ps -a

      - name: Test with pytest
        env:
          APP_NAME: "CNLearn Testing"
          VERSION: 0.0.5
          SERVER_NAME: localhost
          SERVER_HOST: http://127.0.0.1:8000
          POSTGRES_SERVER: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: cnlearn
          TESTING: 1
        run: |
          poetry run pytest

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@master
        with:
          path-to-lcov: "./cov.info"
          github-token: ${{ secrets.GITHUB_TOKEN }}
